
# see https://github.com/apache/rocketmq-externals/tree/master/rocketmq-docker

# rocketmq-nameserver
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rocketmq-ns-deployment
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-nameserver
      name: rocketmq-nameserver
  template:
    metadata:
     labels:
      app: rocketmq-nameserver
      name: rocketmq-nameserver
    spec:
      nodeSelector:
        rocketmq: 'true'
      containers:
      - name: rocketmq-nameserver
        image: rocketmqinc/rocketmq:4.4.0
        command: ["sh","mqnamesrv"]
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        env:
        - name: JAVA_OPT_EXT
          value: "-Xmx1024M -Xms768M -Xss256K"  
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
        #volumeMounts:
        #  - mountPath: /data/rocketmq/logs
        #    name: namesrvlogs
        #  - mountPath: /data/rocketmq/store
        #    name: namesrvstore
      volumes:
      - name: namesrvlogs
        emptyDir: {}
      - name: namesrvstore 
        hostPath:
          path: /data/rocketmq/store

---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-rocketmq-ns
  name: service-rocketmq-ns
  namespace: rocketmq
spec:
  #type: NodePort
  ports:
  - name: http
    port: 9876
    #nodePort: 30019
  selector:
    app: rocketmq-nameserver
    name: rocketmq-nameserver
---
# rocketmq-broker
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rocketmq-broker-deployment
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker
      name: rocketmq-broker
  template:
    metadata:
     labels:
      app: rocketmq-broker
      name: rocketmq-broker
    spec:
      nodeSelector:
        rocketmq: 'true'
      containers:
      - name: rocketmq-broker
        image: rocketmqinc/rocketmq:4.4.0
        securityContext:
          privileged: true
        command: #["sh","-c","mqbroker", "-n","service-rocketmq-ns.rocketmq:9876"]
        - /bin/sh
        - -c
        - curl http://k8s-resource.oss-cn-hangzhou.aliyuncs.com/k8s-deployment/rocketmq/broker-run-pro.sh | sh
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10909
          - containerPort: 10911
        env:
        - name: JAVA_OPT_EXT
          value: "-Xmx1024M -Xms768M -Xss256K"
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
        volumeMounts:
          - mountPath: /root/logs
            name: brokerlogs
          - mountPath: /root/store
            name: brokerstore
      volumes:
      - name: brokerlogs
        emptyDir: {}
      - name: brokerstore
        hostPath:
          path: /data/rocketmq/store
      securityContext:
        runAsUser: 0
        fsGroup: 0   
---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-rocketmq-broker
  name: service-rocketmq-broker
  namespace: rocketmq
spec:
  #type: NodePort
  ports:
  - name: "port10909"
    port: 30020
    #nodePort: 30020
  - name: "port10911"
    port: 30022
    #nodePort: 30022
  selector:
    app: rocketmq-broker
    name: rocketmq-broker


