
# see https://github.com/apache/rocketmq-externals/tree/master/rocketmq-console

# rocketmq-console
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rocketmq-console-deployment
  namespace: rocketmq
spec:
  replicas: 
  selector:
    matchLabels:
      app: rocketmq-console
  template:
    metadata:
     labels:
      app: rocketmq-console
    spec:
      containers:
      - name: rocketmq-console
        image: styletang/rocketmq-console-ng
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: -Drocketmq.namesrv.addr=service-rocketmq-ns.rocketmq:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Xmx384M -Xms384M -Xss256K
        # 资源限制
        resources:
          # 最小申请量
          requests:
            cpu: 50m
            memory: 1024Mi
          # 最大资源限制（并不是绝对的）
          limits:
            cpu: 2000m
            memory: 2048Mi
---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-rocketmq-console
  name: service-rocketmq-console
  namespace: rocketmq
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30021
  selector:
    app: rocketmq-console